version: "3.9"

services:
  nginx:
    container_name: ca-nginx
    image: nginx:1.23.1
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - php

  php:
    container_name: ca-php
    # image: php:8.1.1-fpm-alpine3.15
    build: ./docker/php/
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    # tty: true
    depends_on:
      - mariadb
      - mysql

  mariadb:
    container_name: ca-mariadb
    image: mariadb:10.9
    env_file:
        - ./docker/mysql/.env
    volumes:
        - ./docker/mysql/data/mariadb:/var/lib/mysql
    ports:
        - 3307:3306

  # mysql:
  #     container_name: ca-mysql
  #     image: mysql:8.0
  #     env_file:
  #         - ./docker/mysql/.env
  #     volumes:
  #         - ./docker/mysql/data/mysql:/var/lib/mysql
  #     ports:
  #         - 3308:3306  