<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <link rel="stylesheet" href="./styles/app.css">
    <title>Registracija</title>
</head>

<body>
    <main>
        <div class="row">
            <section class="col-12 col-xl-6">
                <div class="vruler mx-2 my-4" id="userRegistration">
                    <h1>Registracija į kursus</h1>
                    <hr>

                    <form id="userProfileForm" method="POST" enctype="multipart/form-data">
                        <div>
                            <div class="row">
                                <div class="col-3 col-sm-2">
                                    <p>Vardas*:</p>
                                </div>
                                <div class="col-9 col-sm-10">
                                    <input class="form-control" type="text" name="name" value="<?php echo isset($response['error']) && isset($_POST['name']) ? $_POST['name'] : ''; ?>">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-3 col-sm-2">
                                    <p class="align-middle">Pavardė*:</p>
                                </div>
                                <div class="col-9 col-sm-10">
                                    <input class="form-control" type="text" name="lastname" value="<?php echo isset($response['error']) && isset($_POST['lastname']) ? $_POST['lastname'] : ''; ?>">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-3 col-sm-2">
                                    <p>Miestas*:</p>
                                </div>
                                <div class="col-9 col-sm-10">
                                    <select class="form-select" name="city">
                                        <?php foreach ($cities as $id => $city) : ?>
                                            <option <?php echo isset($response['error']) && isset($_POST['city']) && $_POST['city'] == $id ? 'selected' : '' ?> value="<?php echo $city; ?>"><?php echo $city; ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="coding-langs mt-4">
                            <h5>Programavimo kalba*:</h5>
                            <?php foreach ($codingLangs as $id => $lang) : ?>
                                <p class="m-1"><?php echo $lang; ?>
                                    <input class="form-check-input" type="checkbox" name="coding_lang[]" value="<?php echo $lang; ?>" <?php if (isset($response['error']) && isset($_POST['coding_lang'])) : ?> <?php foreach ($_POST['coding_lang'] as $setCodingLang) : ?> <?php echo ($setCodingLang == $lang) ? 'checked' : ''; ?> <?php endforeach; ?> <?php endif; ?>>
                                </p>
                            <?php endforeach; ?>
                        </div>
                        <div class="photo mt-4">
                            <h5>Nuotrauka*:</h5>
                            <input class="form-control" type="file" name="profile_photo">
                        </div>
                        <div class="mt-4">
                            <h5>Papildoma informacija:</h5>
                            <textarea class="form-control" name="additional_info" rows="5" placeholder="Pvz.: turite C++ programavimo patirties"><?php echo isset($response['error']) && isset($_POST['additional_info']) ? $_POST['additional_info'] : '' ?></textarea>
                        </div>
                        <div class="mt-4">
                            <button class="btn btn-primary px-5 py-2" id="submitForm">Siųsti</button>
                        </div>
                    </form>

                    <div class="messages mt-4">

                    </div>
                </div>
            </section>

            <section class="col-12 col-xl-6">
                <div class="m-5 profile" id="userProfile">
                </div>
            </section>
        </div>
    </main>

    <script src="./js/app.js"></script>
</body>

</html>