<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="./styles/app.css">
    <title>Profilis</title>
</head>

<body>
    <main>
        <div class="container m-3">
            <h1>Profilis</h1>

            <div class="card w-75">
                <img src="<?php echo $photoDir ?>" class="card-img-top" alt="profile_img">
                <div class="card-body">
                    <h5 class="card-title bg-light p-2"><?php echo "{$_POST['name']} {$_POST['lastname']}"; ?></h5>
                    <p class="card-text">Miestas: <?php echo $cities[$_POST['city']]; ?></p>
                    <p class="card-text mb-0"> Kalbos: 
                        <?php foreach ($_POST['coding_lang'] as $lang): ?>
                            <p class="m-0"><?php echo $lang;?></p>
                        <?php endforeach; ?>
                    </p>
                    <p class="card-text">Papildoma info: <?php echo $_POST['additional_info']; ?></p>
                </div>
            </div>
        </div>

    </main>
</body>

</html>