<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?php echo asset('/css/app.css'); ?>">
    <title><?php echo $name; ?></title>
</head>

<body>
    <div class="container mt-3">
        <main>
            <h4><?php echo $name; ?></h4>
            <p><?php echo $description; ?></p>
            <div>
                <input type="hidden" name="quizz_name" value="<?php echo $quizzName; ?>">
                <div class="card mt-4 d-none" id="quizzQuestion">
                        <!-- Question content -->
                        <?php echo $cardContent ?? ''; ?>
                        <!-- ./ -->
                    </div>
                    <button class="btn btn-primary mt-4 float-end d-none" id="btnNext">Next</button>
                </div>
                <div id=divContinue>
                    <p>You have already started this quizz, but not yet finished. Would you like to continue from where you left off?</p>
                    <input type="hidden" name="next_q_no" value="<?php echo $nextQuizzQNo;?>">
                    <button class="btn btn-primary" id="btnContinue">Continue</button>
                </div>
            </div>
        </main>
    </div>

    <script src="<?php echo asset('/js/app.js'); ?>"></script>
</body>

</html>
