<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?php echo asset('/css/app.css'); ?>">
    <title><?php echo $name; ?></title>
</head>

<body>
    <div class="container mt-3">
        <main>
            <h4><?php echo $name; ?></h4>
            <p class="p-0">Quizz results:</p>
            <p class="p-0">Possible max points: <?php echo $totalPossiblePoints;?></p>
            <p class="p-0">Correct answers: <?php echo $totalPoints;?> <?php echo sprintf('(%s%%)', round((($totalPoints/$totalPossiblePoints)*100)), 2); ?></p>
        </main>
        <a class="btn btn-primary" href="/">Home</a>
    </div>

    

    <script src="<?php echo asset('/js/app.js'); ?>"></script>
</body>

</html>