<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?php echo asset('/css/app.css'); ?>">
    <title><?php echo $name; ?></title>
</head>

<body>
    <div class="container mt-3">
        <main>
            <h4><?php echo $name; ?></h4>
            <p><?php echo $description; ?></p>
            <a class="btn btn-primary" id="quizzStart" href="<?php echo sprintf('/quizz/%s/1', $quizzName); ?>">Start</a>
        </main>
    </div>

    <script src="<?php echo asset('/js/app.js'); ?>"></script>
</body>

</html>