<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./styles/app.css">
    <title>Registracija</title>
</head>
<body>
    <main>
        <div class="container">
            <h1>Registracija į kursus</h1>
            <hr>

            <form action="" method="POST">
                <p>Vardas: <input type="text" name="name" value="<?= isset($messages['error']) && isset($_POST['name']) ? $_POST['name'] : ''; ?>"></p>
                <p>Pavardė: <input type="text" name="lastname" value="<?= isset($messages['error']) && isset($_POST['lastname']) ? $_POST['lastname'] : ''; ?>"></p>
                <p>Miestas: 
                    <select name="city">
                        <?php foreach ($cities as $city): ?>
                        <option value="<?= $city; ?>"><?= $city; ?></option>
                        <?php endforeach; ?>
                    </select>
                </p>
                <div class="coding-langs">
                    <h3>Programavimo kalba:</h3>
                    <?php foreach ($codingLangs as $lang): ?>
                    <p><?= $lang; ?> <input type="checkbox" name="coding_lang[]" value="<?= $lang; ?>"></p>
                    <?php endforeach; ?>
                </div>
                <h4>Papildoma informacija</h4>
                <textarea name="additional_info" cols="35" rows="5" placeholder="Pvz.: turite C++ programavimo patirties"></textarea>
                <p><button type="submit" name="reg_form" value="submitted">Siųsti</button></p>
            </form>
            
            <?php if (count($messages)): ?>
            <div class="messages">
                <?php if (isset($messages['error'])): ?>
                    <p class="error"><?= $messages['msgStr']; ?></p>
                <?php elseif (isset($messages['success'])): ?>
                    <p class="success"><?= $messages['msgStr']; ?></p>
                <?php endif; ?>
            </div>
            
            <?php endif; ?>
        </div>
    </main>
</body>
</html>