<div class="card text-bg-light">
    <div class="card-body">
        <div class="row align-items-top justify-content-center">
            <div class="col-12 col-md-9 col-lg-10">
                <div class="my-2">
                    <input name="search_inpt" type="search" class="form-control fs-5 text-lowercase" id="searchBarInpt" aria-describedby="searchBarSpan" placeholder="Your link, i.e.: http://example.com">
                </div>
            </div>
            <div class="col-12 col-md-3 col-lg-2">
                <button type="button" class="btn btn-primary w-100 my-2 py-2" id="searchBtn">Generate</button>
            </div>
        </div>
        <div class="messages"></div>
    </div>
</div>